# docker-compose.test.yml (測試環境)
version: '3.8'

services:
  api-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: go test ./... -v
    environment:
      - APP_ENV=test
      - DB_HOST=db-test
      - REDIS_HOST=redis-test
    depends_on:
      - db-test
      - redis-test
    volumes:
      - ./backend:/app

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm test -- --coverage --watchAll=false
    environment:
      - NODE_ENV=test
      - CI=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db-test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=freelance_platform_test
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    tmpfs:
      - /var/lib/postgresql/data

  redis-test:
    image: redis:7-alpine
    tmpfs:
      - /data
